### PR TITLE
Fixes issue #3998, #3971 and  #3968

### PR DESCRIPTION
**Pull request by fabihaahmed**
Fixed three issues related to screen reader.

### CODE REVIEW

**Comment by joshuazeltser** [comment]
#3998 and #3968 look great. With #3971 why does it say checkbox? Shouldn't it say something like file filter?

**Comment by fabihaahmed** [comment]
@joshuazeltser I added an extra span element by mistake which was reading "checkbox". However, it's not related to this issue as this issue deals with providing appropriate tooltip which is working atm.

**Comment by fabihaahmed** [comment]
Gonna push the changes now.

**Comment by joshuazeltser** [comment]
All looks good now

**Comment by joshuazeltser** [comment]
Looks good now

**Pull request merged**
